# -*- coding: utf-8 -*-
"""Print_condition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13d6JSf-RSMsXpMVUjLrNSmMVkcfsA8UK
"""

print(12)

print(45.55)

print('data science')

"""- `creating the relation between str with other data types like -> [int | float | str]`"""

print('My name is john and My age is 29')

"""- `1. Using , ->  comma -> operator `

only 20% of developers will use this techniques in real-time
"""

f = 29
print('My name is john and My age is',f)

subject = 'data science'
duration = 6
time = 1.5

# I am learning data science for 6 months daily 1.5 hours of class


print('I am learning',subject,'for',duration,'months daily',time,'hours of class')

"""- `2. using + operator`

        - `+ operator is not going to create one tab space defaultly`
        - `to Maintain the relation everything should be str only ..`

        this technique will not be used in real time..
"""

f = 29
print('My name is john and My age is '+str(f))

subject = 'data science'
duration = 6
time = 1.5

# I am learning data science for 6 months daily 1.5 hours of class


print('I am learning '+subject+' for '+str(duration)+' months daily '+str(time)+' hours of class')

"""- `3. using idemtifiers -> `
          
          - int -> %d
          - float -> %f
          - str -> %s

          will be not used in real time
"""

f = 29
print('My name is John and My age is %d'%(f))

subject = 'data science'
duration = 6
time = 1.5

# I am learning data science for 6 months daily 1.5 hours of class


print('I am learning %s for %d months dailly %f hours of class'%(subject,duration,time))

subject = 'data science'
duration = 6
time = 1.5

# I am learning data science for 6 months daily 1.5 hours of class

print('I am learning %s for %d months dailly %f hours of class'%(time,duration,subject))

"""- `4. using {} and f-function`"""

f = 29

print(f'My name is John and My age is {f}')

subject = 'data science'
duration = 6
time = 1.5

# I am learning data science for 6 months daily 1.5 hours of class

print(f'I am learning {subject} for {duration} months daily {time} hours of class')

import math # opening the box

sol = math.factorial(6)

print(f'The Factorial of a given Number is : {sol}')

print(f'The Factorial of a given Number is : {math.factorial(6)}')

# difference between \n and \t
# \n means next line
# \t means 2 tab space

print('Jan\nFeb\nMarch')

print('Jan\tFeb\tMarch')

a = 121  #

b = a%10
c = a//10

d = c%10
e = c//10

print(b+d+e)

'ab' + 'jd'

'10' + '20'

a = 457
b = a%10
c = a//10

d = c % 10
e = c // 10

h = str(b)+str(d)+str(e)
print(int(h))

